### ISSUE TITLE
npy files in indoor dataset

### ISSUE THREAD

**Issue by MeNinaa** [chenhsuanlin/spatial-transformer-GAN#24]
Hi,

can you please explain to me why some of the npy files in the dataset have different lengths (this is test dataset): 
`>>> a=np.load('perturb.npy')
>>> b=np.load('disocclude.npy')
>>> a.shape
(8258, 120, 160, 3)
>>> b.shape
(2826, 120, 160, 3)
` 
And what is the goal of using randIdx and randIdxGT during training

Thanks
Best regards
Maria

**Comment by chenhsuanlin** [comment]
Sorry for the late reply. The length of `disocclude.npy` corresponds to the number of objects/scenes, and the length of `perturb.npy` is the number of generated perturbations (in the 3D space) from these objects. Since there may be multiple generated perturbations per each objects, the length of `perturb.npy` (as well as `perturb_mask.npy`) is larger than `disocclude.npy` (as well as `remove.npy`, `indiv_mask.npy`, and `idx_corresp.npy`).

In the code, `randIdx` randomly samples from the pre-generated dataset of 3D-perturbed objects, and `randIdxGT` associates them to the indices of the corresponding rendered scene through `idx_corresp`.

**Comment by MeNinaa** [comment]
Thanks!
