### ISSUE TITLE
Resolution loss on output?

### ISSUE THREAD

**Issue by MeNinaa** [chenhsuanlin/spatial-transformer-GAN#29]
Hi

I noticed a big resolution loss from input to output images. Could you please give me an idea why? Would it be something in the warp process?

Thanks
Best regards
Maria

**Comment by chenhsuanlin** [comment]
I'm not exactly sure what you mean by resolution loss, could you please elaborate on this? Thanks!

**Comment by MeNinaa** [comment]
Hi,

thanks for the reply and apologies for the confusion. By resolution loss I mean the output image (in my case, the furniture) loses some details when compared to the input image. 
In the indoor case, it doesn't matter, but I am using your code to warp some images, and the result is more clear: 
![image](https://user-images.githubusercontent.com/7231598/63281494-bf372c80-c2a4-11e9-953c-8efcc41fe4fa.png)
![image](https://user-images.githubusercontent.com/7231598/63281513-c8c09480-c2a4-11e9-9837-e60bbe2c0c36.png)
Where the former is the input and the latter is the output. 
Please let me know if you need further clarification
Thanks and best regards

**Comment by chenhsuanlin** [comment]
Image warping will always result in some extent of information loss due to sampling, which will make the warped image look a little blurry. This would be more noticeable when the image resolution is low but almost negligible if the resolution were high. So I think this result is pretty much expected.
(If you're not sure, you could also try comparing the warping result with that from scikit-image for a sanity check)
